User.create!([
  {level: 1, surname: "Bernard", name: "Moret", email: "cadibiss@gmail.com", password_digest: "$2a$10$u62mbNxCXZ3kchayJ3uef.GYKYP1BZtOXw3sbUmko.Cm5SQxCXOu.", birthday: "2017-03-04", parents: "Jean-Noël Moret\r\n0796286991\r\nRue des Bonnes-Luites 61\r\n1920 Martigny", photo_url: "players/bernardmoret.jpg", injured: true, injury_archive: "Ligaments croisés (2012)\r\nAducteurs (2011)", suspended: false, cards_archive: "03.04.2017 jaune\r\n20.02.2017 jaune\r\n15.12.2016 rouge", role: 1, school: "Calvin", school_archive: "None", physic_char: "1m80\r\n80kg", playtime: 59, arriving_date: "2017-03-04", endcontrat_date: "2017-03-04", sportactivity_archive: "None", reset_digest: "$2a$10$8B61IAL1ZY6vPWxb45ZdIOc0pDCHG0txV//4OfcwFpmhiDDjVsTHy", reset_sent_at: "2017-03-08 17:37:45", avatar: nil},
  {level: 2, surname: "Benjamin", name: "Besnard", email: "benjamin.besnard@sfc.ch", password_digest: "$2a$10$/a0LPrbOgfVYJREXm61vg.y1dWqep/E6C32lnXzm8hWKyyxtpq5d.", birthday: "2012-02-18", parents: "", photo_url: "", injured: false, injury_archive: "", suspended: false, cards_archive: "", role: 1, school: "", school_archive: "", physic_char: "", playtime: nil, arriving_date: "2017-03-28", endcontrat_date: "2017-03-28", sportactivity_archive: "", reset_digest: nil, reset_sent_at: nil, avatar: nil},
  {level: 2, surname: "Anthony", name: "Sauthier", email: "anthony.sauthier@sfc.ch", password_digest: "$2a$10$UCftI2eF9cv6w9c6Laf0zeN0bOd07zfeTpnblBybczOkOP8h7Pede", birthday: "2017-03-28", parents: "", photo_url: "", injured: false, injury_archive: "", suspended: false, cards_archive: "", role: nil, school: "", school_archive: "", physic_char: "", playtime: nil, arriving_date: "2017-03-28", endcontrat_date: "2017-03-28", sportactivity_archive: "", reset_digest: nil, reset_sent_at: nil, avatar: "201617-besnard.jpg"},
  {level: 3, surname: "Jeremy", name: "Frick", email: "jeremy.fric@sfc.ch", password_digest: "$2a$10$dosfIu8YwNOwUFyhz5OyG.n00p0G2xv1KWEbRJvqziKvLVP.pNXZK", birthday: "2017-03-28", parents: "", photo_url: "", injured: false, injury_archive: "", suspended: false, cards_archive: "", role: nil, school: "", school_archive: "", physic_char: "", playtime: nil, arriving_date: "2017-03-28", endcontrat_date: "2017-03-28", sportactivity_archive: "", reset_digest: nil, reset_sent_at: nil, avatar: nil},
  {level: 3, surname: "Liassine", name: "Cadamuro", email: "liassine.cadamuro@sfc.ch", password_digest: "$2a$10$HwmgY9oZ2dq1yJidGHNkB.cJpPHJ2rGQSDJvmNfnDnd7A.ENafmTC", birthday: "2017-03-28", parents: "", photo_url: "", injured: false, injury_archive: "", suspended: false, cards_archive: "", role: nil, school: "", school_archive: "", physic_char: "", playtime: nil, arriving_date: "2017-03-28", endcontrat_date: "2017-03-28", sportactivity_archive: "", reset_digest: nil, reset_sent_at: nil, avatar: nil},
  {level: 3, surname: "Jérémy", name: "Faug-Porret", email: "jeremy.faug@sfc.ch", password_digest: "$2a$10$Ne2F9RrgAuf4An3to7E5peE6ZqtEq9qWZpQqfLZdGMQY9CmyNW6zm", birthday: "2017-03-28", parents: "", photo_url: "", injured: false, injury_archive: "", suspended: false, cards_archive: "", role: nil, school: "", school_archive: "", physic_char: "", playtime: nil, arriving_date: "2017-03-28", endcontrat_date: "2017-03-28", sportactivity_archive: "", reset_digest: nil, reset_sent_at: nil, avatar: nil},
  {level: 3, surname: "Ousmane", name: "Doumbia", email: "ousmane.doumbia@sfc.ch", password_digest: "$2a$10$GHmZeRZPYlA.KpFrcxSJye71ukDJk7PWfrb0TmM2VQm1Lf4UOxNYu", birthday: "2017-03-28", parents: "", photo_url: "", injured: false, injury_archive: "", suspended: false, cards_archive: "", role: nil, school: "", school_archive: "", physic_char: "", playtime: nil, arriving_date: "2017-03-28", endcontrat_date: "2017-03-28", sportactivity_archive: "", reset_digest: nil, reset_sent_at: nil, avatar: nil},
  {level: 3, surname: "Yassin", name: "Maouche", email: "yassin.maouche@sfc.ch", password_digest: "$2a$10$1AGkC6JV0WqtSh4sck8B5.cexFkd2ODXObtyzHR5.cZE564T2KuVi", birthday: "2017-03-28", parents: "", photo_url: "", injured: false, injury_archive: "", suspended: false, cards_archive: "", role: nil, school: "", school_archive: "", physic_char: "", playtime: nil, arriving_date: "2017-03-28", endcontrat_date: "2017-03-28", sportactivity_archive: "", reset_digest: nil, reset_sent_at: nil, avatar: nil},
  {level: 3, surname: "Bruno", name: "Caslei", email: "bruno.caslei@sfc.ch", password_digest: "$2a$10$RLua8MhhH7eISD63GoxQF.2lMT0v.QfI8HvZPIUZcSid//cXXntD2", birthday: "2017-03-28", parents: "", photo_url: "", injured: false, injury_archive: "", suspended: false, cards_archive: "", role: nil, school: "", school_archive: "", physic_char: "", playtime: nil, arriving_date: "2017-03-28", endcontrat_date: "2017-03-28", sportactivity_archive: "", reset_digest: nil, reset_sent_at: nil, avatar: nil},
  {level: 3, surname: "Florian", name: "Berischa", email: "florian.berische@sfc.ch", password_digest: "$2a$10$ONke4Tah4SYr4gqG7MC1zOwxxUMj98fPO144Bd/HmUNdPg7hRFWuS", birthday: "2017-03-28", parents: "", photo_url: "", injured: false, injury_archive: "", suspended: false, cards_archive: "", role: nil, school: "", school_archive: "", physic_char: "", playtime: nil, arriving_date: "2017-03-28", endcontrat_date: "2017-03-28", sportactivity_archive: "", reset_digest: nil, reset_sent_at: nil, avatar: nil},
  {level: 2, surname: "Meho", name: "Kodro", email: "meho.kodro@sfc.ch", password_digest: "$2a$10$xSPrW0lSvARMVU8PY.TvfuWlNFoHn6a/CbV8PurYJwfpBKrpuu0iW", birthday: "2017-03-28", parents: "", photo_url: "", injured: false, injury_archive: "", suspended: false, cards_archive: "", role: nil, school: "", school_archive: "", physic_char: "", playtime: nil, arriving_date: "2017-03-28", endcontrat_date: "2017-03-28", sportactivity_archive: "", reset_digest: nil, reset_sent_at: nil, avatar: nil}
])
